/**
 * Maestro AI — Alpine.js application logic.
 * i18n: all 6 languages inline. No fetch/XHR needed. Works with file:// protocol.
 */
(function() {
  // ── All translations inline ──
  const LANGUAGES = {
    en: {
      "app.title": "Maestro AI","app.subtitle": "Roast Controller",
      "nav.dashboard": "Dashboard","nav.roast": "Roast","nav.profiles": "Profiles",
      "nav.analysis": "Analysis","nav.batches": "Batches","nav.pid": "PID",
      "nav.tools": "Tools","nav.diagnostics": "Diagnostics","nav.settings": "Settings",
      "dashboard.title": "Dashboard","dashboard.lastRoast": "Last Roast","dashboard.noData": "No roast data yet. Start a new roast!",
      "dashboard.activeSessions": "Active Sessions","dashboard.savedProfiles": "Saved Profiles",
      "dashboard.serverTime": "Server Time","dashboard.status": "System Status",
      "roast.title": "Roast Monitor","roast.start": "Start Roast","roast.stop": "Drop & Stop","roast.end": "✓ END","roast.mark": "✓ Mark","roast.addSample": "Add Sample",
      "roast.bt": "BT","roast.et": "ET","roast.ror": "RoR","roast.time": "Time","roast.phase": "Phase","roast.event": "Event",
      "roast.delta": "Delta (BT-ET)","roast.dtr": "DTR %","roast.chargeTemp": "Charge Temp",
      "roast.heaterPower": "Heater Power","roast.airflow": "Airflow",
      "roast.extraChannels": "Extra Channels","roast.scale": "Scale","roast.alarmSets": "Alarm Sets",
      "roast.setName": "Set name","roast.customLabel": "Custom label","roast.eventLabel": "Event label","roast.aiProfile": "AI Roast Profile",
      "roast.addChannel": "Add channel","roast.fcEvent": "FC Start",
      "roast.spikeFilter": "Spike Filter","roast.medianFilter": "Median",
      "profiles.title": "Profiles","profiles.list": "Profile List","profiles.empty": "No saved profiles","profiles.delete": "Delete",
      "profiles.designer.title": "Target Curve Designer","profiles.designer.create": "Create Target",
      "profiles.properties": "Properties","profiles.save": "Save","profiles.apply": "Apply",
      "profiles.import": "Import","profiles.export": "Export","profiles.filename": "Filename","profiles.paste": "Paste content","profiles.dropHere": "Drop .maestro, .alog or .json file here","profiles.or": "— or —",
      "profiles.sign": "Sign","profiles.verify": "Verify","profiles.keys": "Keys",
      "profiles.privateKey": "Private key","profiles.publicKey": "Public key",
      "profiles.transformer": "Transformer","profiles.factor": "Factor",
      "profiles.phaseRanges": "Phase Ranges","profiles.saveRanges": "Save",
      "profiles.importExport": "Import / Export","profiles.signing": "Signing",
      "analysis.cupping": "Cupping","analysis.energyReport": "Energy Report",
      "analysis.blockchain": "Blockchain","analysis.reports": "Reports",
      "profiles.title": "Profiles","profiles.list": "Profile List","profiles.empty": "No saved profiles","profiles.delete": "Delete",
      "profiles.designer.title": "Target Curve Designer","profiles.designer.create": "Create Target",
      "analysis.title": "Analysis","analysis.stats": "Statistics","analysis.compare": "Compare","analysis.compute": "Compute",
      "analysis.dtr": "DTR","analysis.auc": "AUC","analysis.weightLoss": "Weight Loss",
      "analysis.drying": "Drying","analysis.maillard": "Maillard","analysis.development": "Development",
      "batches.title": "Batches","batches.counter": "Batch Counter","batches.set": "Set","batches.production": "Production",
      "pid.title": "PID Controller","pid.status": "Status",
      "diagnostics.title": "Diagnostics","diagnostics.status": "System Status","diagnostics.logs": "Event Log",
      "diagnostics.server": "Server","diagnostics.device": "Device","diagnostics.test": "Test Device",
      "diagnostics.online": "Online","diagnostics.offline": "Offline","diagnostics.uptime": "Uptime",
      "settings.title": "Settings","settings.language": "Language","settings.temperatureUnit": "Temperature Unit",
      "settings.celsius": "°C","settings.fahrenheit": "°F","settings.server": "Server URL","settings.reset": "Reset Defaults",
      "settings.preferences": "Preferences","settings.guiMode": "GUI Mode","settings.modeMonitoring": "Monitoring","settings.modeEasy": "Easy","settings.modeFull": "Full",
      "settings.enterPin": "Enter PIN","settings.unlock": "Unlock","settings.cancel": "Cancel","settings.changePin": "Change PIN","settings.currentPin": "Current PIN","settings.newPin": "New PIN","settings.confirmPin": "Confirm PIN","settings.savePin": "Save","settings.removePin": "Remove PIN","settings.uiScale": "UI Scale","settings.uiNormal": "Normal","settings.uiLarge": "Large",
      "roast.monitoringBanner": "MONITORING MODE — Read-only view",
      "hardware.emergencyStop": "Emergency Stop",
      "hardware.emergencyStopDesc": "Immediately stops hardware and ends any active roast session. Use for emergencies only.",
      "hardware.emergencyStopConfirm": "EMERGENCY STOP — Stop all hardware and end active session?",
      "pid.tuning": "Tuning","pid.simulate": "Simulate","pid.kp": "Kp","pid.ki": "Ki","pid.kd": "Kd","pid.setpoint": "Setpoint","pid.steps": "Steps",
      "analysis.compareTitle": "Compare","analysis.getReport": "Get Report","analysis.timestamp": "Timestamp","analysis.roastReport": "Roast","analysis.prodReport": "Production",
      "batches.total": "Total","batches.greenKg": "Green (kg)","batches.avgLoss": "Avg Loss %",
      "identity.machineIdentity": "Machine Identity","identity.cloudEndpoint": "Cloud endpoint","identity.init": "Initialize Identity","identity.command": "Command","identity.payload": "Payload",
      "identity.send": "Send","identity.exportKey": "Export Key","identity.trainModel": "Train Model","identity.status": "Status",
      "calc.title": "Calculator","calc.temp": "Temp","calc.weight": "Weight","calc.extractionYield": "Extraction Yield","calc.density": "Density",
      "calc.beverageG": "Beverage g","calc.tds": "TDS %","calc.coffeeG": "Coffee g","calc.weightG": "Weight g","calc.volumeMl": "Volume ml",
      "roast.spikeFilter": "Spike Filter","roast.medianFilter": "Median","roast.cooling": "Cooling",
      "roast.batchEnd": "Batch End","roast.autoSave": "AutoSave","roast.sample": "+ Sample",
      "roast.turningPoint": "TP — Turning Point","roast.dryEnd": "Dry End","roast.fcEnd": "FC End","roast.scStart": "SC Start","roast.drop": "⏹ Drop",
      "roast.namePlaceholder": "Name","roast.btPlaceholder": "BT","roast.etPlaceholder": "ET",
      "roast.densityPlaceholder": "Density g/L","roast.moisturePlaceholder": "Moisture %","roast.agtronPlaceholder": "Agtron","roast.glossary": "Glossary","roast.glossaryBt": "Bean Temperature — internal bean temperature measured by a thermocouple in the coffee bed","roast.glossaryEt": "Environment Temperature — drum air temperature, measures the thermal energy being supplied","roast.glossaryRor": "Rate of Rise — BT rise speed in °C/min, calculated as ΔBT/Δt","roast.glossaryDtr": "Development Time Ratio — percentage of total time spent in the post-FC development phase","roast.glossaryDelta": "Delta BT-ET — difference between bean and environment temperature","roast.glossaryAuc": "Area Under Curve — integral of temperature over time, total energy applied","roast.glossaryFc": "First Crack — exothermic reaction marking the start of development","roast.glossarySc": "Second Crack — indicates advanced roast, oils migrating to surface","roast.glossaryDrying": "Water evaporation phase, bean yellowing (up to ~160°C)","roast.glossaryMaillard": "Browning reactions, flavour development (160-180°C)","roast.glossaryDevelopment": "Post-FC phase, acid reduction, body development",
      "tools.nir": "NIR Spectrometer","tools.nirSession": "Session ID","tools.nirWavelengths": "Wavelengths (comma-sep)","tools.nirIntensities": "Intensities (comma-sep)","tools.nirRecord": "Record","tools.nirGet": "Get Recent",
      "tools.crack": "Crack Detection","tools.crackAmplitude": "Amplitude","tools.crackTime": "Time (s)","tools.crackThreshold": "Threshold","tools.crackDetect": "Detect","tools.crackSetThreshold": "Set Threshold","tools.crackReset": "Reset","tools.crackCount": "Crack count",
      "tools.heating": "Hybrid Heating","tools.heatingTraditional": "Traditional %","tools.heatingMicrowave": "Microwave %","tools.heatingInfrared": "Infrared %","tools.heatingFrequency": "IR Freq (Hz)","tools.heatingApply": "Apply","tools.heatingStatus": "Status",
      "instruments.title": "External Instruments",
      "instruments.variacControl": "Variac Control",
      "instruments.variacOutput": "Output Voltage",
      "instruments.variacSet": "Set Voltage (V)",
      "instruments.apply": "Apply",
      "tools.physicalTools": "Physical Tools & References",
      "tools.agtronChart": "Agtron Color Chart",
      "tools.agtronDesc": "Compare ground coffee against a disk color chart for objective roast degree (#25=dark to #100+=light). Standard in specialty coffee.",
      "tools.triangulator": "Triangulator (Sampler)",
      "tools.triangulatorDesc": "Metal tray that slides into the drum to extract bean samples mid-roast without opening the door. Evaluate colour and smell in real time.",
      "tools.roastLog": "Roast Log Sheet",
      "tools.roastLogDesc": "Printable form to record batch, weather, times, temperatures, and sensory notes by hand. Never loses data.",
      "tools.printLog": "🖨️ Print Log",
      "tools.ambient": "Ambient Conditions",
      "tools.ambientHumidity": "Humidity",
      "tools.ambientPressure": "Pressure",
      "tools.ambientTemp": "Temp",
      "profiles.chargeTemp": "Charge °C","profiles.dryTemp": "Dry °C","profiles.fcTemp": "FC °C","profiles.dropTempLabel": "Drop °C",
      "profiles.dryEndLabel": "Dry End °C","profiles.fcStartLabel": "FC Start °C","profiles.scStartLabel": "SC Start °C",
      "profiles.weightIn": "Weight In (g)","profiles.weightOut": "Weight Out (g)","profiles.color": "Color",
      "profiles.timeScale": "Time Scale","profiles.tempOffset": "Temp Offset","profiles.invert": "Invert","profiles.ctof": "C→F",
      "profiles.factorPlaceholder": "Factor"
    },
    it: {
      "app.title": "Maestro AI","app.subtitle": "Controllo Tostatura",
      "nav.dashboard": "Dashboard","nav.roast": "Tostatura","nav.profiles": "Profili",
      "nav.analysis": "Analisi","nav.batches": "Lotti","nav.pid": "PID",
      "nav.tools": "Strumenti","nav.diagnostics": "Diagnostica","nav.settings": "Impostazioni",
      "dashboard.title": "Dashboard","dashboard.lastRoast": "Ultima Tostatura","dashboard.noData": "Nessun dato. Inizia una tostatura!",
      "dashboard.activeSessions": "Sessioni Attive","dashboard.savedProfiles": "Profili Salvati",
      "dashboard.serverTime": "Ora Server","dashboard.status": "Stato Sistema",
      "roast.title": "Monitor Tostatura","roast.start": "Avvia","roast.stop": "Ferma","roast.end": "✓ Fine","roast.mark": "✓ Segna","roast.addSample": "Aggiungi",
      "roast.bt": "BT","roast.et": "ET","roast.ror": "RoR","roast.time": "Tempo","roast.phase": "Fase","roast.event": "Evento",
      "roast.delta": "Delta (BT-ET)","roast.dtr": "DTR %","roast.chargeTemp": "Temp Carico",
      "roast.heaterPower": "Potenza","roast.airflow": "Flusso Aria",
      "roast.extraChannels": "Canali Extra","roast.scale": "Bilancia","roast.alarmSets": "Set Allarmi",
      "roast.setName": "Nome set","roast.customLabel": "Etichetta","roast.eventLabel": "Etichetta evento","roast.aiProfile": "Profilo AI Tostatura",
      "roast.addChannel": "Aggiungi canale","roast.fcEvent": "FC Start",
      "profiles.title": "Profili","profiles.list": "Elenco","profiles.empty": "Nessun profilo","profiles.delete": "Elimina",
      "profiles.designer.title": "Progettazione Curva","profiles.designer.create": "Crea",
      "profiles.properties": "Proprietà","profiles.save": "Salva","profiles.apply": "Applica",
      "profiles.import": "Importa","profiles.export": "Esporta","profiles.filename": "Nome file","profiles.paste": "Incolla contenuto","profiles.dropHere": "Trascina file .maestro, .alog o .json qui","profiles.or": "— oppure —",
      "profiles.sign": "Firma","profiles.verify": "Verifica","profiles.keys": "Genera Chiavi",
      "profiles.privateKey": "Chiave privata","profiles.publicKey": "Chiave pubblica",
      "profiles.transformer": "Trasformatore","profiles.factor": "Fattore",
      "profiles.phaseRanges": "Range Fasi","profiles.saveRanges": "Salva",
      "profiles.importExport": "Importa / Esporta","profiles.signing": "Firma",
      "analysis.cupping": "Cupping","analysis.energyReport": "Report Energetico",
      "analysis.blockchain": "Blockchain","analysis.reports": "Report",
      "analysis.title": "Analisi","analysis.stats": "Statistiche","analysis.compare": "Confronta","analysis.compute": "Calcola",
      "analysis.dtr": "DTR","analysis.auc": "AUC","analysis.weightLoss": "Perdita Peso",
      "analysis.drying": "Asciugatura","analysis.maillard": "Maillard","analysis.development": "Sviluppo",
      "batches.title": "Lotti","batches.counter": "Contatore","batches.set": "Imposta","batches.production": "Produzione",
      "pid.title": "Controllore PID","pid.status": "Stato",
      "diagnostics.title": "Diagnostica","diagnostics.status": "Stato Sistema","diagnostics.logs": "Registro",
      "diagnostics.server": "Server","diagnostics.device": "Dispositivo","diagnostics.test": "Test",
      "diagnostics.online": "Online","diagnostics.offline": "Offline","diagnostics.uptime": "Attivo",
      "settings.title": "Impostazioni","settings.language": "Lingua","settings.temperatureUnit": "Unità Temperatura",
      "settings.celsius": "°C","settings.fahrenheit": "°F","settings.server": "URL Server","settings.reset": "Ripristina",
      "settings.preferences": "Preferenze","settings.guiMode": "Modalità GUI","settings.modeMonitoring": "Monitoraggio","settings.modeEasy": "Facile","settings.modeFull": "Completa",
      "settings.enterPin": "Inserisci PIN","settings.unlock": "Sblocca","settings.cancel": "Annulla","settings.changePin": "Cambia PIN","settings.currentPin": "PIN attuale","settings.newPin": "Nuovo PIN","settings.confirmPin": "Conferma PIN","settings.savePin": "Salva","settings.removePin": "Rimuovi PIN","settings.uiScale": "Scala UI","settings.uiNormal": "Normale","settings.uiLarge": "Grande",
      "roast.monitoringBanner": "MODALITA MONITORAGGIO — Solo visualizzazione",
      "hardware.emergencyStop": "Arresto Macchina",
      "hardware.emergencyStopDesc": "Arresta immediatamente l'hardware e termina qualsiasi sessione attiva. Solo per emergenze.",
      "hardware.emergencyStopConfirm": "ARRESTO MACCHINA — Fermare tutto l'hardware e terminare la sessione attiva?",
      "pid.tuning": "Regolazione","pid.simulate": "Simula","pid.kp": "Kp","pid.ki": "Ki","pid.kd": "Kd","pid.setpoint": "Setpoint","pid.steps": "Passi",
      "analysis.compareTitle": "Confronta","analysis.getReport": "Ottieni Report","analysis.timestamp": "Timestamp","analysis.roastReport": "Tostatura","analysis.prodReport": "Produzione",
      "batches.total": "Totale","batches.greenKg": "Verde (kg)","batches.avgLoss": "Perdita Media %",
      "identity.machineIdentity": "Identità Macchina","identity.cloudEndpoint": "Endpoint cloud","identity.init": "Inizializza Identità","identity.command": "Comando","identity.payload": "Payload",
      "identity.send": "Invia","identity.exportKey": "Esporta Chiave","identity.trainModel": "Addestra Modello","identity.status": "Stato",
      "calc.title": "Calcolatrice","calc.temp": "Temp","calc.weight": "Peso","calc.extractionYield": "Resa Estrazione","calc.density": "Densità",
      "calc.beverageG": "Bevanda g","calc.tds": "TDS %","calc.coffeeG": "Caffè g","calc.weightG": "Peso g","calc.volumeMl": "Volume ml",
      "roast.spikeFilter": "Filtro Spike","roast.medianFilter": "Mediano","roast.cooling": "Raffredd.",
      "roast.batchEnd": "Fine Lotto","roast.autoSave": "AutoSalva","roast.sample": "+ Campione",
      "roast.turningPoint": "TP — Punto di Svolta","roast.dryEnd": "Fine Asciug.","roast.fcEnd": "FC Fine","roast.scStart": "SC Inizio","roast.drop": "⏹ Scarico",
      "roast.namePlaceholder": "Nome","roast.btPlaceholder": "BT","roast.etPlaceholder": "ET",
      "roast.densityPlaceholder": "Densità g/L","roast.moisturePlaceholder": "Umidità %","roast.agtronPlaceholder": "Agtron","roast.glossary": "Glossario","roast.glossaryBt": "Bean Temperature — temperatura interna del chicco, misurata da termocoppia nel letto di caffè","roast.glossaryEt": "Environment Temperature — temperatura ambiente del tamburo, misura l'energia termica fornita","roast.glossaryRor": "Rate of Rise — velocità di salita della BT in °C/min, calcolata come ΔBT/Δt","roast.glossaryDtr": "Development Time Ratio — percentuale del tempo totale dedicato alla fase di sviluppo post-FC","roast.glossaryDelta": "Delta BT-ET — differenza tra temperatura chicco e ambiente","roast.glossaryAuc": "Area Under Curve — integrale della temperatura nel tempo, energia totale applicata","roast.glossaryFc": "First Crack — primo crack, reazione esotermica che segna l'inizio dello sviluppo","roast.glossarySc": "Second Crack — secondo crack, indica tostatura avanzata","roast.glossaryDrying": "Fase di essiccazione, evaporazione dell'acqua (fino a ~160°C)","roast.glossaryMaillard": "Reazioni di brunitura, sviluppo di aromi (160-180°C)","roast.glossaryDevelopment": "Fase post-FC, riduzione acidità, sviluppo corpo",
      "tools.nir": "Spettrometro NIR","tools.nirSession": "ID Sessione","tools.nirWavelengths": "Lunghezze d'onda (sep. virgola)","tools.nirIntensities": "Intensità (sep. virgola)","tools.nirRecord": "Registra","tools.nirGet": "Recenti",
      "tools.crack": "Rilevamento Crack","tools.crackAmplitude": "Ampiezza","tools.crackTime": "Tempo (s)","tools.crackThreshold": "Soglia","tools.crackDetect": "Rileva","tools.crackSetThreshold": "Imposta Soglia","tools.crackReset": "Resetta","tools.crackCount": "Conteggio crack",
      "tools.heating": "Riscaldamento Ibrido","tools.heatingTraditional": "Tradizionale %","tools.heatingMicrowave": "Microonde %","tools.heatingInfrared": "Infrarossi %","tools.heatingFrequency": "Freq IR (Hz)","tools.heatingApply": "Applica","tools.heatingStatus": "Stato",
      "instruments.title": "Strumenti Esterni",
      "instruments.variacControl": "Controllo Variac",
      "instruments.variacOutput": "Tensione Uscita",
      "instruments.variacSet": "Set Tensione (V)",
      "instruments.apply": "Applica",
      "tools.physicalTools": "Strumenti Fisici e Riferimenti",
      "tools.agtronChart": "Cartella Colori Agtron",
      "tools.agtronDesc": "Confronta il caffè macinato con una cartella a dischi per il grado di tostatura oggettivo (#25=scuro a #100+=chiaro). Standard nel caffè specialty.",
      "tools.triangulator": "Campionatore (Triangolatore)",
      "tools.triangulatorDesc": "Vassoietto metallico che scorre nel tamburo per prelevare campioni di chicchi durante la tostatura senza aprire lo sportello. Valuta colore e odore in tempo reale.",
      "tools.roastLog": "Scheda di Tostatura",
      "tools.roastLogDesc": "Modulo stampabile per annotare a penna lotto, condizioni atmosferiche, tempi, temperature e note sensoriali. Non perde mai dati.",
      "tools.printLog": "🖨️ Stampa Scheda",
      "tools.ambient": "Condizioni Ambientali",
      "tools.ambientHumidity": "Umidità",
      "tools.ambientPressure": "Pressione",
      "tools.ambientTemp": "Temp",
      "profiles.chargeTemp": "Carico °C","profiles.dryTemp": "Asciug. °C","profiles.fcTemp": "FC °C","profiles.dropTempLabel": "Scarico °C",
      "profiles.dryEndLabel": "Fine Asciug. °C","profiles.fcStartLabel": "FC Inizio °C","profiles.scStartLabel": "SC Inizio °C",
      "profiles.weightIn": "Peso In (g)","profiles.weightOut": "Peso Out (g)","profiles.color": "Colore",
      "profiles.timeScale": "Scala Tempo","profiles.tempOffset": "Offset Temp","profiles.invert": "Inverti","profiles.ctof": "C→F",
      "profiles.factorPlaceholder": "Fattore"
    },
    es: {
      "app.title": "Maestro AI","app.subtitle": "Control de Tostado",
      "nav.dashboard": "Panel","nav.roast": "Tostado","nav.profiles": "Perfiles","nav.analysis": "Análisis",
      "nav.batches": "Lotes","nav.pid": "PID","nav.tools": "Herramientas","nav.diagnostics": "Diagnóstico","nav.settings": "Ajustes",
      "dashboard.title": "Panel Principal","dashboard.lastRoast": "Último Tostado","dashboard.noData": "¡Sin datos!",
      "dashboard.activeSessions": "Sesiones","dashboard.savedProfiles": "Perfiles Guardados","dashboard.serverTime": "Hora",
      "roast.title": "Monitor","roast.start": "Iniciar","roast.stop": "Parar","roast.end": "✓ Fin","roast.mark": "✓ Marcar","roast.addSample": "Añadir",
      "roast.bt": "BT","roast.et": "ET","roast.ror": "RoR","roast.time": "Tiempo","roast.phase": "Fase",
      "roast.delta": "Delta (BT-ET)","roast.dtr": "DTR %","roast.chargeTemp": "Temp Carga",
      "roast.heaterPower": "Potencia","roast.airflow": "Flujo Aire",
      "roast.extraChannels": "Canales Extras","roast.scale": "Báscula","roast.alarmSets": "Conj. Alarma",
      "roast.setName": "Nombre","roast.customLabel": "Etiqueta","roast.eventLabel": "Etiqueta evento","roast.aiProfile": "Perfil AI",
      "roast.addChannel": "Añadir canal","roast.fcEvent": "Inicio FC",
      "roast.spikeFilter": "Filtro Spike","roast.medianFilter": "Mediana","roast.cooling": "Enfriamiento",
      "roast.batchEnd": "Fin Lote","roast.autoSave": "AutoGuardar","roast.sample": "+ Muestra",
      "roast.turningPoint": "TP — Punto de Giro","roast.dryEnd": "Fin Secado","roast.fcEnd": "Fin FC","roast.scStart": "Inicio SC","roast.drop": "⏹ Soltar",
      "roast.namePlaceholder": "Nombre","roast.btPlaceholder": "BT","roast.etPlaceholder": "ET",
      "roast.densityPlaceholder": "Densidad g/L","roast.moisturePlaceholder": "Humedad %","roast.agtronPlaceholder": "Agtron",
      "profiles.title": "Perfiles","profiles.list": "Lista","profiles.empty": "Sin perfiles","profiles.delete": "Eliminar",
      "profiles.designer.title": "Diseñador de Curva","profiles.designer.create": "Crear Objetivo",
      "profiles.properties": "Propiedades","profiles.save": "Guardar","profiles.apply": "Aplicar",
      "profiles.import": "Importar","profiles.export": "Exportar","profiles.filename": "Nombre","profiles.paste": "Pegar contenido","profiles.dropHere": "Suelte archivo .maestro, .alog o .json aquí","profiles.or": "— o —",
      "profiles.sign": "Firmar","profiles.verify": "Verificar","profiles.keys": "Generar Claves",
      "profiles.privateKey": "Clave privada","profiles.publicKey": "Clave pública",
      "profiles.transformer": "Transformador","profiles.factor": "Factor",
      "profiles.phaseRanges": "Rangos de Fase","profiles.saveRanges": "Guardar",
      "profiles.importExport": "Importar / Exportar","profiles.signing": "Firma",
      "profiles.chargeTemp": "Carga °C","profiles.dryTemp": "Secado °C","profiles.fcTemp": "FC °C","profiles.dropTempLabel": "Soltar °C",
      "profiles.dryEndLabel": "Fin Secado °C","profiles.fcStartLabel": "Inicio FC °C","profiles.scStartLabel": "Inicio SC °C",
      "profiles.weightIn": "Peso Inicial (g)","profiles.weightOut": "Peso Final (g)","profiles.color": "Color",
      "profiles.timeScale": "Escala Tiempo","profiles.tempOffset": "Despl. Temp","profiles.invert": "Invertir","profiles.ctof": "C→F",
      "profiles.factorPlaceholder": "Factor",
      "analysis.title": "Análisis","analysis.stats": "Estadísticas","analysis.compare": "Comparar","analysis.compute": "Calcular",
      "analysis.cupping": "Catación","analysis.energyReport": "Informe Energético","analysis.blockchain": "Blockchain","analysis.reports": "Informes",
      "analysis.dtr": "DTR","analysis.auc": "AUC","analysis.weightLoss": "Pérdida Peso",
      "analysis.drying": "Secado","analysis.maillard": "Maillard","analysis.development": "Desarrollo",
      "analysis.compareTitle": "Comparar","analysis.getReport": "Obtener Informe","analysis.timestamp": "Marca Tiempo","analysis.roastReport": "Tostado","analysis.prodReport": "Producción",
      "batches.title": "Lotes","batches.counter": "Contador","batches.set": "Fijar","batches.production": "Producción",
      "batches.total": "Total","batches.greenKg": "Verde (kg)","batches.avgLoss": "Pérdida Media %",
      "pid.title": "Controlador PID","pid.status": "Estado",
      "pid.tuning": "Ajuste","pid.simulate": "Simular","pid.kp": "Kp","pid.ki": "Ki","pid.kd": "Kd","pid.setpoint": "Consigna","pid.steps": "Pasos",
      "diagnostics.title": "Diagnóstico","diagnostics.status": "Estado","diagnostics.logs": "Registro",
      "diagnostics.server": "Servidor","diagnostics.device": "Dispositivo","diagnostics.test": "Probar",
      "diagnostics.online": "En Línea","diagnostics.offline": "Fuera de Línea","diagnostics.uptime": "Activo",
      "hardware.emergencyStop": "Parada de Emergencia","hardware.emergencyStopDesc": "Detiene inmediatamente el hardware y finaliza cualquier sesión activa. Solo para emergencias.","hardware.emergencyStopConfirm": "PARADA DE EMERGENCIA — ¿Detener todo el hardware y finalizar la sesión activa?",
      "settings.title": "Ajustes","settings.language": "Idioma","settings.temperatureUnit": "Unidad",
      "settings.celsius": "°C","settings.fahrenheit": "°F","settings.server": "URL","settings.reset": "Restaurar",
      "settings.preferences": "Preferencias","settings.guiMode": "Modo GUI","settings.modeMonitoring": "Monitoreo","settings.modeEasy": "Fácil","settings.modeFull": "Completo",
      "settings.enterPin": "Ingresar PIN","settings.unlock": "Desbloquear","settings.cancel": "Cancelar","settings.changePin": "Cambiar PIN","settings.currentPin": "PIN actual","settings.newPin": "Nuevo PIN","settings.confirmPin": "Confirmar PIN","settings.savePin": "Guardar","settings.removePin": "Eliminar PIN","settings.uiScale": "Escala UI","settings.uiNormal": "Normal","settings.uiLarge": "Grande",
      "roast.monitoringBanner": "MODO MONITOREO — Solo lectura",
      "roast.glossary": "Glosario","roast.glossaryBt": "Bean Temperature — temperatura interna del grano, medida por un termopar en el lecho de café","roast.glossaryEt": "Environment Temperature — temperatura ambiente del tambor, mide la energía térmica suministrada","roast.glossaryRor": "Rate of Rise — velocidad de subida de BT en °C/min, calculada como ΔBT/Δt","roast.glossaryDtr": "Development Time Ratio — porcentaje del tiempo total en la fase de desarrollo post-FC","roast.glossaryDelta": "Delta BT-ET — diferencia entre temperatura del grano y ambiente","roast.glossaryAuc": "Area Under Curve — integral de la temperatura en el tiempo, energía total aplicada","roast.glossaryFc": "First Crack — reacción exotérmica que marca el inicio del desarrollo","roast.glossarySc": "Second Crack — indica tostado avanzado, aceites migrando a la superficie","roast.glossaryDrying": "Fase de evaporación del agua,amarilleo del grano (hasta ~160°C)","roast.glossaryMaillard": "Reacciones de dorado, desarrollo de sabor (160-180°C)","roast.glossaryDevelopment": "Fase post-FC, reducción de acidez, desarrollo del cuerpo",
      "tools.nir": "Espectrómetro NIR","tools.nirSession": "ID Sesión","tools.nirWavelengths": "Longitudes (sep. coma)","tools.nirIntensities": "Intensidades (sep. coma)","tools.nirRecord": "Registrar","tools.nirGet": "Obtener Recientes",
      "tools.crack": "Detección de Crack","tools.crackAmplitude": "Amplitud","tools.crackTime": "Tiempo (s)","tools.crackThreshold": "Umbral","tools.crackDetect": "Detectar","tools.crackSetThreshold": "Fijar Umbral","tools.crackReset": "Reiniciar","tools.crackCount": "Conteo cracks",
      "tools.heating": "Calentamiento Híbrido","tools.heatingTraditional": "Tradicional %","tools.heatingMicrowave": "Microondas %","tools.heatingInfrared": "Infrarrojos %","tools.heatingFrequency": "Frec IR (Hz)","tools.heatingApply": "Aplicar","tools.heatingStatus": "Estado",
      "instruments.title": "Instrumentos Externos",
      "instruments.variacControl": "Control Variac",
      "instruments.variacOutput": "Tensión Salida",
      "instruments.variacSet": "Ajustar Voltaje (V)",
      "instruments.apply": "Aplicar",
      "tools.physicalTools": "Herramientas Físicas y Referencias",
      "tools.agtronChart": "Tabla Colores Agtron",
      "tools.agtronDesc": "Compare el café molido con una tabla de discos para el grado de tostado objetivo (#25=oscuro a #100+=claro). Estándar en café specialty.",
      "tools.triangulator": "Muestreador (Triangulador)",
      "tools.triangulatorDesc": "Bandeja metálica que se desliza en el tambor para extraer muestras durante el tostado sin abrir la puerta. Evalúe color y olor en tiempo real.",
      "tools.roastLog": "Hoja de Tostado",
      "tools.roastLogDesc": "Formulario imprimible para anotar lote, clima, tiempos, temperaturas y notas sensoriales a mano. Nunca pierde datos.",
      "tools.printLog": "🖨️ Imprimir Hoja",
      "tools.ambient": "Condiciones Ambientales",
      "tools.ambientHumidity": "Humedad",
      "tools.ambientPressure": "Presión",
      "tools.ambientTemp": "Temp",
      "identity.machineIdentity": "Identidad Máquina","identity.cloudEndpoint": "Endpoint nube","identity.init": "Inicializar Identidad","identity.command": "Comando","identity.payload": "Carga útil",
      "identity.send": "Enviar","identity.exportKey": "Exportar Clave","identity.trainModel": "Entrenar Modelo","identity.status": "Estado",
      "calc.title": "Calculadora","calc.temp": "Temp","calc.weight": "Peso","calc.extractionYield": "Rendimiento Extracción","calc.density": "Densidad",
      "calc.beverageG": "Bebida g","calc.tds": "TDS %","calc.coffeeG": "Café g","calc.weightG": "Peso g","calc.volumeMl": "Volumen ml"
    },
    fr: {
      "app.title": "Maestro AI","app.subtitle": "Contrôle de Torréfaction",
      "nav.dashboard": "Tableau","nav.roast": "Torréfaction","nav.profiles": "Profils","nav.analysis": "Analyse",
      "nav.batches": "Lots","nav.pid": "PID","nav.tools": "Outils","nav.diagnostics": "Diagnostic","nav.settings": "Paramètres",
      "dashboard.title": "Tableau","dashboard.lastRoast": "Dernière Torréfaction","dashboard.noData": "Aucune donnée",
      "roast.title": "Moniteur","roast.start": "Démarrer","roast.stop": "Arrêter","roast.end": "✓ Fin","roast.mark": "✓ Marquer","roast.addSample": "Ajouter",
      "roast.bt": "BT","roast.et": "ET","roast.ror": "RoR","roast.time": "Temps","roast.phase": "Phase",
      "profiles.title": "Profils","profiles.list": "Liste","profiles.empty": "Aucun profil","profiles.delete": "Supprimer",
      "profiles.designer.title": "Concepteur de Courbe","profiles.designer.create": "Créer Cible",
      "profiles.properties": "Propriétés","profiles.save": "Sauvegarder","profiles.apply": "Appliquer",
      "profiles.import": "Importer","profiles.export": "Exporter","profiles.filename": "Fichier","profiles.paste": "Coller contenu","profiles.dropHere": "Déposez un fichier .maestro, .alog ou .json ici","profiles.or": "— ou —",
      "profiles.sign": "Signer","profiles.verify": "Vérifier","profiles.keys": "Générer Clés",
      "profiles.privateKey": "Clé privée","profiles.publicKey": "Clé publique",
      "profiles.transformer": "Transformateur","profiles.factor": "Facteur",
      "profiles.phaseRanges": "Plages de Phase","profiles.saveRanges": "Sauvegarder",
      "profiles.importExport": "Importer / Exporter","profiles.signing": "Signature",
      "analysis.cupping": "Dégustation","analysis.energyReport": "Rapport Énergétique","analysis.blockchain": "Blockchain","analysis.reports": "Rapports",
      "analysis.title": "Analyse","analysis.stats": "Statistiques","analysis.compare": "Comparer","analysis.compute": "Calculer",
      "analysis.dtr": "DTR","analysis.auc": "AUC","analysis.weightLoss": "Perte de Poids",
      "analysis.drying": "Séchage","analysis.maillard": "Maillard","analysis.development": "Développement",
      "batches.title": "Lots","batches.counter": "Compteur","batches.set": "Définir","batches.production": "Production",
      "pid.title": "Régulateur PID","pid.status": "État",
      "diagnostics.title": "Diagnostic","diagnostics.status": "État","diagnostics.logs": "Journal",
      "diagnostics.server": "Serveur","diagnostics.device": "Périphérique","diagnostics.test": "Tester",
      "diagnostics.online": "En Ligne","diagnostics.offline": "Hors Ligne","diagnostics.uptime": "Actif",
      "hardware.emergencyStop": "Arrêt d'Urgence","hardware.emergencyStopDesc": "Arrête immédiatement le matériel et termine toute session active. Utilisation en cas d'urgence uniquement.","hardware.emergencyStopConfirm": "ARRÊT D'URGENCE — Arrêter tout le matériel et terminer la session active ?",
      "settings.title": "Paramètres","settings.language": "Langue","settings.temperatureUnit": "Unité",
      "settings.celsius": "°C","settings.fahrenheit": "°F","settings.server": "URL","settings.reset": "Réinitialiser",
      "settings.preferences": "Préférences","settings.guiMode": "Mode GUI","settings.modeMonitoring": "Surveillance","settings.modeEasy": "Facile","settings.modeFull": "Complet",
      "settings.enterPin": "Saisir PIN","settings.unlock": "Déverrouiller","settings.cancel": "Annuler","settings.changePin": "Changer PIN","settings.currentPin": "PIN actuel","settings.newPin": "Nouveau PIN","settings.confirmPin": "Confirmer PIN","settings.savePin": "Enregistrer","settings.removePin": "Supprimer PIN","settings.uiScale": "Échelle UI","settings.uiNormal": "Normale","settings.uiLarge": "Grande",
      "roast.monitoringBanner": "MODE SURVEILLANCE — Lecture seule",
      "pid.tuning": "Réglage","pid.simulate": "Simuler","pid.kp": "Kp","pid.ki": "Ki","pid.kd": "Kd","pid.setpoint": "Consigne","pid.steps": "Pas",
      "analysis.compareTitle": "Comparer","analysis.getReport": "Rapport","analysis.timestamp": "Horodatage","analysis.roastReport": "Torréfaction","analysis.prodReport": "Production",
      "batches.total": "Total","batches.greenKg": "Vert (kg)","batches.avgLoss": "Perte Moy. %",
      "identity.machineIdentity": "Identité Machine","identity.cloudEndpoint": "Endpoint cloud","identity.init": "Initialiser","identity.command": "Commande","identity.payload": "Payload",
      "identity.send": "Envoyer","identity.exportKey": "Exporter Clé","identity.trainModel": "Entraîner","identity.status": "Statut",
      "calc.title": "Calculatrice","calc.temp": "Temp","calc.weight": "Poids","calc.extractionYield": "Rendement","calc.density": "Densité",
      "calc.beverageG": "Boisson g","calc.tds": "TDS %","calc.coffeeG": "Café g","calc.weightG": "Poids g","calc.volumeMl": "Volume ml",
      "roast.spikeFilter": "Filtre Spike","roast.medianFilter": "Médian","roast.cooling": "Refroid.",
      "roast.batchEnd": "Fin Lot","roast.autoSave": "AutoSauve","roast.sample": "+ Éch.",
      "roast.turningPoint": "TP — Point de Virage","roast.dryEnd": "Fin Séch.","roast.fcEnd": "FC Fin","roast.scStart": "SC Début","roast.drop": "⏹ Lâcher",
      "roast.namePlaceholder": "Nom","roast.btPlaceholder": "BT","roast.etPlaceholder": "ET",
      "roast.densityPlaceholder": "Densité g/L","roast.moisturePlaceholder": "Humidité %","roast.agtronPlaceholder": "Agtron","roast.glossary": "Glossaire","roast.glossaryBt": "Bean Temperature — température interne du grain par thermocouple","roast.glossaryEt": "Environment Temperature — température air tambour","roast.glossaryRor": "Rate of Rise — vitesse BT en °C/min (ΔBT/Δt)","roast.glossaryDtr": "Development Time Ratio — % temps post-FC","roast.glossaryDelta": "Delta BT-ET — différence grain/environnement","roast.glossaryAuc": "Area Under Curve — énergie totale appliquée","roast.glossaryFc": "First Crack — réaction exothermique","roast.glossarySc": "Second Crack — torréfaction avancée","roast.glossaryDrying": "Évaporation eau, jaunissement (~160°C)","roast.glossaryMaillard": "Brunissement, développement arômes (160-180°C)","roast.glossaryDevelopment": "Post-FC, réduction acidité, corps",
      "tools.nir": "Spectromètre NIR","tools.nirSession": "ID Session","tools.nirWavelengths": "Long. onde (virgule)","tools.nirIntensities": "Intensités (virgule)","tools.nirRecord": "Enreg.","tools.nirGet": "Récents",
      "tools.crack": "Détection Crack","tools.crackAmplitude": "Amplitude","tools.crackTime": "Temps (s)","tools.crackThreshold": "Seuil","tools.crackDetect": "Détecter","tools.crackSetThreshold": "Seuil","tools.crackReset": "Reset","tools.crackCount": "Nbre cracks",
      "tools.heating": "Chauffage Hybride","tools.heatingTraditional": "Trad. %","tools.heatingMicrowave": "Micro-ondes %","tools.heatingInfrared": "IR %","tools.heatingFrequency": "Fréq IR (Hz)","tools.heatingApply": "Appliquer","tools.heatingStatus": "État",
      "instruments.title": "Instruments Externes",
      "instruments.variacControl": "Contrôle Variac",
      "instruments.variacOutput": "Tension Sortie",
      "instruments.variacSet": "Tension (V)",
      "instruments.apply": "Appliquer",
      "tools.physicalTools": "Outils et Références",
      "tools.agtronChart": "Tableau Agtron",
      "tools.agtronDesc": "Comparez le café moulu avec un disque colorimétrique (#25=foncé à #100+=clair). Standard specialty.",
      "tools.triangulator": "Échantillonneur",
      "tools.triangulatorDesc": "Plateau métallique pour extraire échantillons en cours de torréfaction.",
      "tools.roastLog": "Fiche Torréfaction",
      "tools.roastLogDesc": "Formulaire papier pour lot, météo, temps, températures. Ne perd jamais les données.",
      "tools.printLog": "🖨️ Imprimer",
      "tools.ambient": "Conditions",
      "tools.ambientHumidity": "Humidité",
      "tools.ambientPressure": "Pression",
      "tools.ambientTemp": "Temp",
      "profiles.chargeTemp": "Charge °C","profiles.dryTemp": "Séch. °C","profiles.fcTemp": "FC °C","profiles.dropTempLabel": "Drop °C",
      "profiles.dryEndLabel": "Fin Séch. °C","profiles.fcStartLabel": "FC Début °C","profiles.scStartLabel": "SC Début °C",
      "profiles.weightIn": "Poids In (g)","profiles.weightOut": "Poids Out (g)","profiles.color": "Couleur",
      "profiles.timeScale": "Échelle Temps","profiles.tempOffset": "Offset Temp","profiles.invert": "Inverser","profiles.ctof": "C→F",
      "profiles.factorPlaceholder": "Facteur"
    },
    de: {
      "app.title": "Maestro AI","app.subtitle": "Röststeuerung",
      "nav.dashboard": "Übersicht","nav.roast": "Röstung","nav.profiles": "Profile","nav.analysis": "Analyse",
      "nav.batches": "Chargen","nav.pid": "PID","nav.tools": "Werkzeuge","nav.diagnostics": "Diagnose","nav.settings": "Einstellungen",
      "dashboard.title": "Übersicht","dashboard.lastRoast": "Letzte Röstung","dashboard.noData": "Keine Daten",
      "roast.title": "Röstmonitor","roast.start": "Starten","roast.stop": "Stoppen","roast.end": "✓ Ende","roast.mark": "✓ Markieren","roast.addSample": "Probe",
      "roast.bt": "BT","roast.et": "ET","roast.ror": "RoR","roast.time": "Zeit","roast.phase": "Phase",
      "profiles.title": "Profile","profiles.list": "Liste","profiles.empty": "Keine Profile","profiles.delete": "Löschen",
      "profiles.designer.title": "Kurven-Designer","profiles.designer.create": "Ziel Erstellen",
      "profiles.properties": "Eigenschaften","profiles.save": "Speichern","profiles.apply": "Anwenden",
      "profiles.import": "Importieren","profiles.export": "Exportieren","profiles.filename": "Dateiname","profiles.paste": "Inhalt einfügen","profiles.dropHere": "Datei .maestro, .alog oder .json hier ablegen","profiles.or": "— oder —",
      "profiles.sign": "Signieren","profiles.verify": "Prüfen","profiles.keys": "Schlüssel Generieren",
      "profiles.privateKey": "Privater Schlüssel","profiles.publicKey": "Öffentlicher Schlüssel",
      "profiles.transformer": "Transformator","profiles.factor": "Faktor",
      "profiles.phaseRanges": "Phasenbereiche","profiles.saveRanges": "Speichern",
      "profiles.importExport": "Import / Export","profiles.signing": "Signatur",
      "analysis.cupping": "Cupping","analysis.energyReport": "Energiebericht","analysis.blockchain": "Blockchain","analysis.reports": "Berichte",
      "analysis.title": "Analyse","analysis.stats": "Statistiken","analysis.compare": "Vergleichen","analysis.compute": "Berechnen",
      "analysis.dtr": "DTR","analysis.auc": "AUC","analysis.weightLoss": "Gewichtsverlust",
      "analysis.drying": "Trocknung","analysis.maillard": "Maillard","analysis.development": "Entwicklung",
      "batches.title": "Chargen","batches.counter": "Zähler","batches.set": "Setzen","batches.production": "Produktion",
      "pid.title": "PID-Regler","pid.status": "Status",
      "diagnostics.title": "Diagnose","diagnostics.status": "Status","diagnostics.logs": "Protokoll",
      "diagnostics.server": "Server","diagnostics.device": "Gerät","diagnostics.test": "Testen",
      "diagnostics.online": "Online","diagnostics.offline": "Offline","diagnostics.uptime": "Betriebszeit",
      "hardware.emergencyStop": "Not-Aus","hardware.emergencyStopDesc": "Stoppt sofort die Hardware und beendet alle aktiven Röstungen. Nur für Notfälle.","hardware.emergencyStopConfirm": "NOT-AUS — Gesamte Hardware stoppen und aktive Sitzung beenden?",
      "settings.title": "Einstellungen","settings.language": "Sprache","settings.temperatureUnit": "Einheit",
      "settings.celsius": "°C","settings.fahrenheit": "°F","settings.server": "Server-URL","settings.reset": "Zurücksetzen",
      "settings.preferences": "Einstellungen","settings.guiMode": "GUI-Modus","settings.modeMonitoring": "Überwachung","settings.modeEasy": "Einfach","settings.modeFull": "Voll",
      "settings.enterPin": "PIN eingeben","settings.unlock": "Entsperren","settings.cancel": "Abbrechen","settings.changePin": "PIN ändern","settings.currentPin": "Aktueller PIN","settings.newPin": "Neuer PIN","settings.confirmPin": "PIN bestätigen","settings.savePin": "Speichern","settings.removePin": "PIN entfernen","settings.uiScale": "UI-Skalierung","settings.uiNormal": "Normal","settings.uiLarge": "Groß",
      "roast.monitoringBanner": "UEBERWACHUNGSMODUS — Nur-Lesen",
      "pid.tuning": "Abstimmung","pid.simulate": "Simulieren","pid.kp": "Kp","pid.ki": "Ki","pid.kd": "Kd","pid.setpoint": "Sollwert","pid.steps": "Schritte",
      "analysis.compareTitle": "Vergleichen","analysis.getReport": "Bericht","analysis.timestamp": "Zeitstempel","analysis.roastReport": "Röstung","analysis.prodReport": "Produktion",
      "batches.total": "Gesamt","batches.greenKg": "Grün (kg)","batches.avgLoss": "Ø Verlust %",
      "identity.machineIdentity": "Maschinen-ID","identity.cloudEndpoint": "Cloud-Endpunkt","identity.init": "Initialisieren","identity.command": "Befehl","identity.payload": "Payload",
      "identity.send": "Senden","identity.exportKey": "Schlüssel Exp.","identity.trainModel": "Trainieren","identity.status": "Status",
      "calc.title": "Rechner","calc.temp": "Temp","calc.weight": "Gewicht","calc.extractionYield": "Extraktionsausbeute","calc.density": "Dichte",
      "calc.beverageG": "Getränk g","calc.tds": "TDS %","calc.coffeeG": "Kaffee g","calc.weightG": "Gewicht g","calc.volumeMl": "Volumen ml",
      "roast.spikeFilter": "Spike-Filter","roast.medianFilter": "Median","roast.cooling": "Kühlung",
      "roast.batchEnd": "Charge Ende","roast.autoSave": "AutoSpeich.","roast.sample": "+ Probe",
      "roast.turningPoint": "TP — Wendepunkt","roast.dryEnd": "Trockn. Ende","roast.fcEnd": "FC Ende","roast.scStart": "SC Beginn","roast.drop": "⏹ Drop",
      "roast.namePlaceholder": "Name","roast.btPlaceholder": "BT","roast.etPlaceholder": "ET",
      "roast.densityPlaceholder": "Dichte g/L","roast.moisturePlaceholder": "Feuchte %","roast.agtronPlaceholder": "Agtron","roast.glossary": "Glossar","roast.glossaryBt": "Bean Temperature — Bohnentemperatur im Kaffeebett","roast.glossaryEt": "Environment Temperature — Trommellufttemperatur","roast.glossaryRor": "Rate of Rise — BT-Anstieg °C/min (ΔBT/Δt)","roast.glossaryDtr": "Development Time Ratio — % Zeit nach FC","roast.glossaryDelta": "Delta BT-ET — Differenz Bohne/Umgebung","roast.glossaryAuc": "Area Under Curve — eingebrachte Energie","roast.glossaryFc": "First Crack — exotherme Reaktion","roast.glossarySc": "Second Crack — fortgeschrittene Röstung","roast.glossaryDrying": "Wasserverdampfung (~160°C)","roast.glossaryMaillard": "Bräunung, Aromaentwicklung (160-180°C)","roast.glossaryDevelopment": "Post-FC, Säurereduktion, Körper",
      "tools.nir": "NIR-Spektrometer","tools.nirSession": "Sitzungs-ID","tools.nirWavelengths": "Wellenlängen (Komma)","tools.nirIntensities": "Intensitäten (Komma)","tools.nirRecord": "Aufnehmen","tools.nirGet": "Letzte",
      "tools.crack": "Crack-Erkennung","tools.crackAmplitude": "Amplitude","tools.crackTime": "Zeit (s)","tools.crackThreshold": "Schwelle","tools.crackDetect": "Erkennen","tools.crackSetThreshold": "Schwelle Setzen","tools.crackReset": "Zurücksetzen","tools.crackCount": "Crack-Zahl",
      "tools.heating": "Hybrid-Heizung","tools.heatingTraditional": "Trad. %","tools.heatingMicrowave": "Mikrowelle %","tools.heatingInfrared": "IR %","tools.heatingFrequency": "IR Freq (Hz)","tools.heatingApply": "Anwenden","tools.heatingStatus": "Status",
      "instruments.title": "Externe Instrumente",
      "instruments.variacControl": "Variac-Steuerung",
      "instruments.variacOutput": "Ausgangsspannung",
      "instruments.variacSet": "Spannung (V)",
      "instruments.apply": "Anwenden",
      "tools.physicalTools": "Werkzeuge & Referenzen",
      "tools.agtronChart": "Agtron-Farbtabelle",
      "tools.agtronDesc": "Vergleichen Sie gemahlenen Kaffee mit Farbscheibe (#25=dunkel bis #100+=hell). Specialty-Standard.",
      "tools.triangulator": "Probennehmer",
      "tools.triangulatorDesc": "Metallschale zur Probenentnahme während der Röstung.",
      "tools.roastLog": "Röstprotokoll",
      "tools.roastLogDesc": "Druckbares Formular. Verliert nie Daten.",
      "tools.printLog": "🖨️ Drucken",
      "tools.ambient": "Umgebung",
      "tools.ambientHumidity": "Feuchte",
      "tools.ambientPressure": "Druck",
      "tools.ambientTemp": "Temp",
      "profiles.chargeTemp": "Charge °C","profiles.dryTemp": "Trock. °C","profiles.fcTemp": "FC °C","profiles.dropTempLabel": "Drop °C",
      "profiles.dryEndLabel": "Trock. Ende °C","profiles.fcStartLabel": "FC Beginn °C","profiles.scStartLabel": "SC Beginn °C",
      "profiles.weightIn": "Einwaage (g)","profiles.weightOut": "Auswaage (g)","profiles.color": "Farbe",
      "profiles.timeScale": "Zeitskala","profiles.tempOffset": "Temp-Offset","profiles.invert": "Invertieren","profiles.ctof": "C→F",
      "profiles.factorPlaceholder": "Faktor"
    },
    ru: {
      "app.title": "Maestro AI","app.subtitle": "Управление Обжаркой",
      "nav.dashboard": "Панель","nav.roast": "Обжарка","nav.profiles": "Профили","nav.analysis": "Анализ",
      "nav.batches": "Партии","nav.pid": "ПИД","nav.tools": "Инструменты","nav.diagnostics": "Диагностика","nav.settings": "Настройки",
      "dashboard.title": "Панель Управления","dashboard.lastRoast": "Последняя Обжарка","dashboard.noData": "Нет данных. Начните новую обжарку!",
      "dashboard.activeSessions": "Активные Сессии","dashboard.savedProfiles": "Сохранённые Профили",
      "dashboard.serverTime": "Время Сервера","dashboard.status": "Состояние Системы",
      "roast.title": "Монитор Обжарки","roast.start": "Начать Обжарку","roast.stop": "Сброс и Стоп","roast.end": "✓ Конец","roast.mark": "✓ Отметить","roast.addSample": "Добавить Точку",
      "roast.bt": "BT","roast.et": "ET","roast.ror": "RoR","roast.time": "Время","roast.phase": "Фаза","roast.event": "Событие",
      "roast.delta": "Дельта (BT-ET)","roast.dtr": "DTR %","roast.chargeTemp": "Тemp Загрузки",
      "roast.heaterPower": "Мощность","roast.airflow": "Поток Воздуха",
      "roast.extraChannels": "Доп. Каналы","roast.scale": "Весы","roast.alarmSets": "Наборы Аварий",
      "roast.setName": "Имя набора","roast.customLabel": "Метка","roast.eventLabel": "Метка события","roast.aiProfile": "AI Профиль",
      "roast.addChannel": "Добавить канал","roast.fcEvent": "Начало FC",
      "profiles.title": "Профили","profiles.list": "Список Профилей","profiles.empty": "Нет профилей","profiles.delete": "Удалить",
      "profiles.designer.title": "Дизайнер Кривой","profiles.designer.create": "Создать Цель",
      "profiles.properties": "Свойства","profiles.save": "Сохранить","profiles.apply": "Применить",
      "profiles.import": "Импорт","profiles.export": "Экспорт","profiles.filename": "Имя файла","profiles.paste": "Вставить","profiles.dropHere": "Перетащите .maestro, .alog или .json","profiles.or": "— или —",
      "profiles.sign": "Подписать","profiles.verify": "Проверить","profiles.keys": "Ключи",
      "profiles.privateKey": "Приватный ключ","profiles.publicKey": "Публичный ключ",
      "profiles.transformer": "Трансформатор","profiles.factor": "Фактор",
      "profiles.phaseRanges": "Диапазоны Фаз","profiles.saveRanges": "Сохранить",
      "profiles.importExport": "Импорт / Экспорт","profiles.signing": "Подпись",
      "analysis.cupping": "Каппинг","analysis.energyReport": "Энергетика",
      "analysis.blockchain": "Блокчейн","analysis.reports": "Отчеты",
      "analysis.title": "Анализ","analysis.stats": "Статистика","analysis.compare": "Сравнить","analysis.compute": "Вычислить",
      "analysis.dtr": "DTR","analysis.auc": "AUC","analysis.weightLoss": "Потеря Веса",
      "analysis.drying": "Сушка","analysis.maillard": "Майяр","analysis.development": "Развитие",
      "batches.title": "Партии","batches.counter": "Счётчик","batches.set": "Установить","batches.production": "Производство",
      "pid.title": "ПИД-Регулятор","pid.status": "Статус",
      "diagnostics.title": "Диагностика","diagnostics.status": "Статус","diagnostics.logs": "Журнал",
      "diagnostics.server": "Сервер","diagnostics.device": "Устройство","diagnostics.test": "Тест",
      "diagnostics.online": "Онлайн","diagnostics.offline": "Офлайн","diagnostics.uptime": "Работа",
      "settings.title": "Настройки","settings.language": "Язык","settings.temperatureUnit": "Единица Темп.",
      "settings.celsius": "°C","settings.fahrenheit": "°F","settings.server": "URL","settings.reset": "Сбросить",
      "settings.preferences": "Настройки","settings.guiMode": "Режим GUI","settings.modeMonitoring": "Мониторинг","settings.modeEasy": "Простой","settings.modeFull": "Полный",
      "settings.enterPin": "Введите PIN","settings.unlock": "Разблокировать","settings.cancel": "Отмена","settings.changePin": "Сменить PIN","settings.currentPin": "Текущий PIN","settings.newPin": "Новый PIN","settings.confirmPin": "Подтвердить PIN","settings.savePin": "Сохранить","settings.removePin": "Удалить PIN","settings.uiScale": "Масштаб UI","settings.uiNormal": "Обычный","settings.uiLarge": "Крупный",
      "roast.monitoringBanner": "РЕЖИМ МОНИТОРИНГА — Только просмотр",
      "hardware.emergencyStop": "Аварийная Остановка",
      "hardware.emergencyStopDesc": "Немедленно останавливает оборудование и завершает активную сессию. Только для экстренных случаев.",
      "hardware.emergencyStopConfirm": "АВАРИЙНАЯ ОСТАНОВКА — Остановить оборудование и завершить сессию?",
      "pid.tuning": "Настройка","pid.simulate": "Симуляция","pid.kp": "Kp","pid.ki": "Ki","pid.kd": "Kd","pid.setpoint": "Уставка","pid.steps": "Шаги",
      "analysis.compareTitle": "Сравнить","analysis.getReport": "Отчет","analysis.timestamp": "Время","analysis.roastReport": "Обжарка","analysis.prodReport": "Производство",
      "batches.total": "Всего","batches.greenKg": "Зеленый (кг)","batches.avgLoss": "Ср. Потеря %",
      "identity.machineIdentity": "Идентификация","identity.cloudEndpoint": "Облачный эндпоинт","identity.init": "Инициализировать","identity.command": "Команда","identity.payload": "Нагрузка",
      "identity.send": "Отправить","identity.exportKey": "Экспорт Ключа","identity.trainModel": "Обучить","identity.status": "Статус",
      "calc.title": "Калькулятор","calc.temp": "Темп","calc.weight": "Вес","calc.extractionYield": "Выход Экстракции","calc.density": "Плотность",
      "calc.beverageG": "Напиток г","calc.tds": "TDS %","calc.coffeeG": "Кофе г","calc.weightG": "Вес г","calc.volumeMl": "Объем мл",
      "roast.spikeFilter": "Spike Фильтр","roast.medianFilter": "Медиана","roast.cooling": "Охлажд.",
      "roast.batchEnd": "Конец Партии","roast.autoSave": "Автосохр.","roast.sample": "+ Точка",
      "roast.turningPoint": "TP — Точка Поворота","roast.dryEnd": "Конец Сушки","roast.fcEnd": "FC Конец","roast.scStart": "SC Начало","roast.drop": "⏹ Сброс",
      "roast.namePlaceholder": "Имя","roast.btPlaceholder": "BT","roast.etPlaceholder": "ET",
      "roast.densityPlaceholder": "Плотность г/л","roast.moisturePlaceholder": "Влажность %","roast.agtronPlaceholder": "Agtron","roast.glossary": "Глоссарий","roast.glossaryBt": "Bean Temperature — температура зерна","roast.glossaryEt": "Environment Temperature — температура барабана","roast.glossaryRor": "Rate of Rise — скорость BT °C/мин","roast.glossaryDtr": "Development Time Ratio — % времени после FC","roast.glossaryDelta": "Delta BT-ET — разница зерно/среда","roast.glossaryAuc": "Area Under Curve — полная энергия","roast.glossaryFc": "First Crack — экзотермическая реакция","roast.glossarySc": "Second Crack — темная обжарка","roast.glossaryDrying": "Испарение воды, пожелтение (~160°C)","roast.glossaryMaillard": "Потемнение, аромат (160-180°C)","roast.glossaryDevelopment": "После FC, кисл-ть↓, тело",
      "tools.nir": "NIR Спектрометр","tools.nirSession": "ID Сессии","tools.nirWavelengths": "Длины волн","tools.nirIntensities": "Интенсивности","tools.nirRecord": "Записать","tools.nirGet": "Последние",
      "tools.crack": "Детекция Crack","tools.crackAmplitude": "Амплитуда","tools.crackTime": "Время (с)","tools.crackThreshold": "Порог","tools.crackDetect": "Детект","tools.crackSetThreshold": "Уст. Порог","tools.crackReset": "Сброс","tools.crackCount": "Кол-во crack",
      "tools.heating": "Гибрид Нагрев","tools.heatingTraditional": "Трад. %","tools.heatingMicrowave": "Микроволны %","tools.heatingInfrared": "ИК %","tools.heatingFrequency": "ИК Частота","tools.heatingApply": "Применить","tools.heatingStatus": "Статус",
      "instruments.title": "Внешние Инструменты","instruments.variacControl": "Управление Вариаком","instruments.variacOutput": "Выходное Напряжение","instruments.variacSet": "Напряжение (V)","instruments.apply": "Применить",
      "tools.physicalTools": "Инструменты","tools.agtronChart": "Таблица Agtron","tools.agtronDesc": "Сравните с диском (#25=темный до #100+=светлый)","tools.triangulator": "Пробоотборник","tools.triangulatorDesc": "Лоток для проб во время обжарки","tools.roastLog": "Журнал","tools.roastLogDesc": "Форма для записи данных","tools.printLog": "🖨️ Печать","tools.ambient": "Окружение","tools.ambientHumidity": "Влажность","tools.ambientPressure": "Давление","tools.ambientTemp": "Темп",
      "profiles.chargeTemp": "Загрузка °C","profiles.dryTemp": "Сушка °C","profiles.fcTemp": "FC °C","profiles.dropTempLabel": "Сброс °C",
      "profiles.dryEndLabel": "Конец Сушки °C","profiles.fcStartLabel": "FC Начало °C","profiles.scStartLabel": "SC Начало °C",
      "profiles.weightIn": "Вес Вх (г)","profiles.weightOut": "Вес Вых (г)","profiles.color": "Цвет",
      "profiles.timeScale": "Шкала Времени","profiles.tempOffset": "Смещение T","profiles.invert": "Инверт.","profiles.ctof": "C→F",
      "profiles.factorPlaceholder": "Фактор"
    }
  };

  // ── Resolve language: saved preference > browser > en ──
  const supported = Object.keys(LANGUAGES);
  let langCode = localStorage.getItem('maestro-lang');
  if (!langCode || !supported.includes(langCode)) {
    langCode = navigator.language?.split('-')[0] || 'en';
    if (!supported.includes(langCode)) langCode = 'en';
  }

  // ── Alpine.js ──
  document.addEventListener('alpine:init', () => {
    Alpine.store('lang', LANGUAGES[langCode]);

    Alpine.magic('t', () => (key) => {
      return Alpine.store('lang')?.[key] ?? key;
    });

    // Language switcher (called from settings panel)
    window.setLanguage = function(code) {
      if (!supported.includes(code)) code = 'en';
      Alpine.store('lang', LANGUAGES[code]);
      localStorage.setItem('maestro-lang', code);
    };
  });
})();

// ── Global Helpers ──
function formatTime(sec) {
  if (sec == null || isNaN(sec)) return '--:--';
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
}
function formatTemp(celsius, unit = 'C') {
  if (celsius == null || isNaN(celsius)) return '---';
  if (unit === 'F') return `${Math.round(celsius * 9 / 5 + 32)}°F`;
  return `${Math.round(celsius)}°C`;
}
function phaseLabel(phase) {
  const map = {
    'pre-charge': 'pre-charge','ramping': 'ramping','drying': 'Drying',
    'maillard': 'Maillard','first-crack': '1st Crack','development': 'Development',
    'second-crack': '2nd Crack','finishing': 'Finishing','cooling': 'Cooling','complete': 'Complete'
  };
  return map[phase] ?? phase;
}
