using System.Text;

namespace Maestro_AI.Services;

using Maestro_AI.Models;

/// <summary>Generates HTML roast reports from profile data.</summary>
public static class ReportGenerator
{
    public static string RoastReport(ProfileData p)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Roast Report</title>");
        sb.AppendLine("<style>body{font-family:sans-serif;max-width:800px;margin:2rem auto;color:#333}");
        sb.AppendLine("h1{color:#c17a2b}table{width:100%;border-collapse:collapse}td,th{padding:0.4rem;border:1px solid #ddd}</style></head><body>");
        sb.AppendLine($"<h1>☕ {HtmlEncode(p.Name)}</h1>");
        sb.AppendLine($"<p><strong>Origin:</strong> {HtmlEncode(p.BeanOrigin)} | <strong>Date:</strong> {p.RoastDate:yyyy-MM-dd} | <strong>Operator:</strong> {HtmlEncode(p.Operator)}</p>");

        if (p.Metrics != null)
        {
            var m = p.Metrics;
            sb.AppendLine("<h2>Metrics</h2><table><tr><th>Metric</th><th>Value</th></tr>");
            sb.AppendLine($"<tr><td>DTR</td><td>{m.DtrPercent:F1}%</td></tr>");
            sb.AppendLine($"<tr><td>Total AUC</td><td>{m.TotalAuc:F0}</td></tr>");
            sb.AppendLine($"<tr><td>Total Roast</td><td>{m.TotalRoastSec / 60:F1} min</td></tr>");
            sb.AppendLine($"<tr><td>Weight Loss</td><td>{m.WeightLossPercent:F1}%</td></tr>");
            sb.AppendLine("</table>");
        }

        if (p.Cupping != null)
        {
            sb.AppendLine($"<h2>Cupping Score: {p.Cupping.TotalScore:F1}/100</h2>");
        }

        sb.AppendLine("<p><small>Generated by Maestro AI</small></p>");
        sb.AppendLine("</body></html>");
        return sb.ToString();
    }

    public static string ProductionReport(List<object> batches)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Production Report</title>");
        sb.AppendLine("<style>body{font-family:sans-serif;max-width:800px;margin:2rem auto}</style></head><body>");
        sb.AppendLine($"<h1>Production Report</h1><p>Total batches: {batches.Count}</p>");
        sb.AppendLine("</body></html>");
        return sb.ToString();
    }

    private static string HtmlEncode(string s) => System.Net.WebUtility.HtmlEncode(s ?? "");
}
